### ISSUE TITLE
Create the course content for the ICP course.

### ISSUE THREAD

**Issue by nathaniawong** [dacadeorg/icp-message-board-contract#1]
https://github.com/dacadeorg/icp-marketplace-rest-api - Repo not public yet. Will make it soon.

Check in on JS agents.

https://github.com/dacadeorg/icp-message-board-contract

**Comment by nathaniawong** [comment]
Moritz and Taras had some issues, @Emmanuel-umeh waiting on that to be resolved before creating course content. Check in with @moritzfelipe on Monday, 5 June.

**Comment by moritzfelipe** [comment]
- [x] Put a gif of the interactions of the final build product.
- [x] Add more gifs where applicable (DFX command line, e.g.)
- [x] Create a final version of the product and make a codespace out of it (put it into the dacade org as a repo)
- [x] Come up with a simple challenge for the course.
- [x] For the intro chapter, find the best video and two articles that explain ICP.

**Comment by nathaniawong** [comment]
Waiting for @moritzfelipe to confirm whether reviewed and merged.

**Comment by moritzfelipe** [comment]
Done
